# Generated by Django 5.2.5 on 2025-09-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('refRayon', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
