# Generated by Django 5.2.5 on 2025-09-04 08:05

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(default=datetime.date(2024, 9, 4)),
        ),
    ]
