# Generated by Django 5.2.5 on 2025-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_remove_contenir_id_contenir_pk_contenir_qte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayon',
            name='nomRayon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
