# Generated by Django 5.2.5 on 2025-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_rayon_nomrayon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='pk',
        ),
        migrations.AddField(
            model_name='contenir',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
