# Generated by Django 5.2.5 on 2025-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0009_remove_contenir_pk_contenir_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='qte',
        ),
        migrations.AddField(
            model_name='contenir',
            name='pk',
            field=models.CompositePrimaryKey('refProd', 'refRayon', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
