# Generated by Django 5.2.5 on 2025-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0010_remove_contenir_id_remove_contenir_qte_contenir_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenir',
            name='Qte',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
